/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnclassifiedRouteImport } from './routes/unclassified'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as RepoOwnerNameRouteImport } from './routes/repo.$owner.$name'
import { Route as DemoRepoOwnerNameRouteImport } from './routes/demo.repo.$owner.$name'

const UnclassifiedRoute = UnclassifiedRouteImport.update({
  id: '/unclassified',
  path: '/unclassified',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoOwnerNameRoute = RepoOwnerNameRouteImport.update({
  id: '/repo/$owner/$name',
  path: '/repo/$owner/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRepoOwnerNameRoute = DemoRepoOwnerNameRouteImport.update({
  id: '/demo/repo/$owner/$name',
  path: '/demo/repo/$owner/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/unclassified': typeof UnclassifiedRoute
  '/demo/': typeof DemoIndexRoute
  '/repo/$owner/$name': typeof RepoOwnerNameRoute
  '/demo/repo/$owner/$name': typeof DemoRepoOwnerNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unclassified': typeof UnclassifiedRoute
  '/demo': typeof DemoIndexRoute
  '/repo/$owner/$name': typeof RepoOwnerNameRoute
  '/demo/repo/$owner/$name': typeof DemoRepoOwnerNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/unclassified': typeof UnclassifiedRoute
  '/demo/': typeof DemoIndexRoute
  '/repo/$owner/$name': typeof RepoOwnerNameRoute
  '/demo/repo/$owner/$name': typeof DemoRepoOwnerNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unclassified'
    | '/demo/'
    | '/repo/$owner/$name'
    | '/demo/repo/$owner/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unclassified'
    | '/demo'
    | '/repo/$owner/$name'
    | '/demo/repo/$owner/$name'
  id:
    | '__root__'
    | '/'
    | '/unclassified'
    | '/demo/'
    | '/repo/$owner/$name'
    | '/demo/repo/$owner/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UnclassifiedRoute: typeof UnclassifiedRoute
  DemoIndexRoute: typeof DemoIndexRoute
  RepoOwnerNameRoute: typeof RepoOwnerNameRoute
  DemoRepoOwnerNameRoute: typeof DemoRepoOwnerNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unclassified': {
      id: '/unclassified'
      path: '/unclassified'
      fullPath: '/unclassified'
      preLoaderRoute: typeof UnclassifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo/$owner/$name': {
      id: '/repo/$owner/$name'
      path: '/repo/$owner/$name'
      fullPath: '/repo/$owner/$name'
      preLoaderRoute: typeof RepoOwnerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/repo/$owner/$name': {
      id: '/demo/repo/$owner/$name'
      path: '/demo/repo/$owner/$name'
      fullPath: '/demo/repo/$owner/$name'
      preLoaderRoute: typeof DemoRepoOwnerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UnclassifiedRoute: UnclassifiedRoute,
  DemoIndexRoute: DemoIndexRoute,
  RepoOwnerNameRoute: RepoOwnerNameRoute,
  DemoRepoOwnerNameRoute: DemoRepoOwnerNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
